---
- name: nodejs playground
  hosts: all

  roles:
    - role: nodesource.node
      become: yes
      tags: node

  tasks:
    - name: backshop-es6 - Install npm packages
      npm:
        global: no
        path: /vagrant
        production: no
        state: latest

